version: 2.1

orbs:
  r: circleci/r@1.1.1

jobs:
  build-and-test:
    docker:
      - image: rocker/verse:4.1.0
    steps:
      - checkout
      - r/install-packages:
          packages: |
            remotes
            testthat
            shiny
            meta
            metafor
            ggplot2
            plotly
            DT
            bslib
            shinyjs
            rmarkdown
            knitr
      - run:
          name: Run tests
          command: |
            R -e 'testthat::test_dir("tests/testthat")'

workflows:
  version: 2
  build-and-test:
    jobs:
      - build-and-test