version: 2.1

jobs:
  install_dependencies:
    docker:
      - image: rocker/verse:4.4.0  # Official R docker image with necessary R packages pre-installed
    steps:
      - checkout

      - run:
          name: Install system dependencies
          command: |
            sudo apt-get update && sudo apt-get install -y \
            libcurl4-openssl-dev \
            libssl-dev \
            libxml2-dev \
            libgeos-dev \
            libproj-dev \
            gdal-bin \
            libgdal-dev \
            libudunits2-dev \
            pandoc \
            pandoc-citeproc

      - restore_cache:
          keys:
            - R-renv-cache-v1-{{ checksum "renv.lock" }}
            - R-renv-cache-v1

      - run:
          name: Restore R environment via renv
          command: |
            R -e "install.packages('renv')"
            R -e "renv::restore()"

      - run:
          name: Run tests
          command: |
            R -e "testthat::test_dir('tests/testthat')"

      - save_cache:
          key: R-renv-cache-v1-{{ checksum "renv.lock" }}
          paths:
            - ~/.cache/R/renv

workflows:
  version: 2
  test_workflow:
    jobs:
      - install_dependencies
