version: 2.1

jobs:
  build-and-test:
    docker:
      - image: rocker/verse:4.1.0
    steps:
      - checkout
      - run:
          name: Run tests
          command: |
            R -e 'testthat::test_dir("tests/testthat")'

workflows:
  version: 2
  build-test:
    jobs:
      - build-and-test