version: 2.1

jobs:
  build:
    docker:
      - image: rocker/verse:4.1.0  # Use a Docker image with R pre-installed
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            R -e 'install.packages(c("shiny", "meta", "metafor", "ggplot2", "plotly", "DT", "bslib", "shinyjs", "rmarkdown", "knitr","gridExtra","sp","sf","testthat"))'
      - run:
          name: Run R script
          command: |
            Rscript test-functions.R  # Replace 'your_script.R' with your actual script filename
      - run:
          name: Run tests
          command: |
            R -e 'testthat::test_dir("tests/testthat")'

workflows:
  version: 2
  build-and-test:
    jobs:
      - build
