version: 2.1

jobs:
  build:
    docker:
      - image: rocker/verse:4.1.0
    steps:
      - checkout
      - run:
          name: Install system dependencies
          command: |
            apt-get update && apt-get install -y \
            libgdal-dev \
            libproj-dev \
            libgeos-dev
      - run:
          name: Restore R package dependencies
          command: |
            R -e 'renv::restore()'
      - run:
          name: Run tests
          command: |
            R -e 'testthat::test_dir("tests/testthat")'

workflows:
  version: 2
  build-and-test:
    jobs:
      - build
