version: 2.1

jobs:
  build:
    docker:
      - image: rocker/verse:4.1.0  # Use a Docker image with R pre-installed
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            R -e 'install.packages(c("remotes", "testthat", "shiny", "meta", "metafor", "ggplot2", "plotly", "DT", "bslib", "shinyjs", "rmarkdown", "knitr"))'
      - run:
          name: Check package
          command: |
            R CMD build .
            R CMD check *.tar.gz --as-cran
      - run:
          name: Run tests
          command: |
            R -e 'testthat::test_dir("tests/testthat")'

workflows:
  version: 2
  build-and-test:
    jobs:
      - build
